project_id = "xiofbauhzbqmienrjljb"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.expire-matches]
verify_jwt = false

[functions.discord-auth-start]
verify_jwt = false

[functions.discord-auth-callback]
verify_jwt = false

[functions.create-stripe-connect-account]
verify_jwt = false

[functions.create-stripe-payout]
verify_jwt = false
