project_id = "xiofbauhzbqmienrjljb"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.expire-matches]
verify_jwt = false
